name: Sniukas
favicon: null
layout_spectrum: 0.50167
typography_spectrum: 0.49499
title: Marc Sniukas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030504'
    - '#d7cfc2'
    - '#ab9180'
    - '#4c5d79'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
