name: Sniukas
favicon: null
layout_spectrum: 0.50167
typography_spectrum: 0.49499
title: Marc Sniukas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7835729729849845
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
